//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrix.MetrixDistributedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusAdLine1ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusAdLine2ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusAdLine3ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusContactValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cusIdValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusNameValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusNicValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusAdLine1Value {
            get {
                return this.cusAdLine1ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusAdLine1ValueField, value) != true)) {
                    this.cusAdLine1ValueField = value;
                    this.RaisePropertyChanged("cusAdLine1Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusAdLine2Value {
            get {
                return this.cusAdLine2ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusAdLine2ValueField, value) != true)) {
                    this.cusAdLine2ValueField = value;
                    this.RaisePropertyChanged("cusAdLine2Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusAdLine3Value {
            get {
                return this.cusAdLine3ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusAdLine3ValueField, value) != true)) {
                    this.cusAdLine3ValueField = value;
                    this.RaisePropertyChanged("cusAdLine3Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusContactValue {
            get {
                return this.cusContactValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusContactValueField, value) != true)) {
                    this.cusContactValueField = value;
                    this.RaisePropertyChanged("cusContactValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cusIdValue {
            get {
                return this.cusIdValueField;
            }
            set {
                if ((this.cusIdValueField.Equals(value) != true)) {
                    this.cusIdValueField = value;
                    this.RaisePropertyChanged("cusIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusNameValue {
            get {
                return this.cusNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusNameValueField, value) != true)) {
                    this.cusNameValueField = value;
                    this.RaisePropertyChanged("cusNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusNicValue {
            get {
                return this.cusNicValueField;
            }
            set {
                if ((object.ReferenceEquals(this.cusNicValueField, value) != true)) {
                    this.cusNicValueField = value;
                    this.RaisePropertyChanged("cusNicValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empAdLine1ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empAdLine2ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empContactValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empDeptValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime empDobValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empIdValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNameValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNicValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empPosValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empAdLine1Value {
            get {
                return this.empAdLine1ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empAdLine1ValueField, value) != true)) {
                    this.empAdLine1ValueField = value;
                    this.RaisePropertyChanged("empAdLine1Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empAdLine2Value {
            get {
                return this.empAdLine2ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empAdLine2ValueField, value) != true)) {
                    this.empAdLine2ValueField = value;
                    this.RaisePropertyChanged("empAdLine2Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empContactValue {
            get {
                return this.empContactValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empContactValueField, value) != true)) {
                    this.empContactValueField = value;
                    this.RaisePropertyChanged("empContactValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empDeptValue {
            get {
                return this.empDeptValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empDeptValueField, value) != true)) {
                    this.empDeptValueField = value;
                    this.RaisePropertyChanged("empDeptValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime empDobValue {
            get {
                return this.empDobValueField;
            }
            set {
                if ((this.empDobValueField.Equals(value) != true)) {
                    this.empDobValueField = value;
                    this.RaisePropertyChanged("empDobValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empIdValue {
            get {
                return this.empIdValueField;
            }
            set {
                if ((this.empIdValueField.Equals(value) != true)) {
                    this.empIdValueField = value;
                    this.RaisePropertyChanged("empIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empNameValue {
            get {
                return this.empNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empNameValueField, value) != true)) {
                    this.empNameValueField = value;
                    this.RaisePropertyChanged("empNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empNicValue {
            get {
                return this.empNicValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empNicValueField, value) != true)) {
                    this.empNicValueField = value;
                    this.RaisePropertyChanged("empNicValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empPosValue {
            get {
                return this.empPosValueField;
            }
            set {
                if ((object.ReferenceEquals(this.empPosValueField, value) != true)) {
                    this.empPosValueField = value;
                    this.RaisePropertyChanged("empPosValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIdValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int purchPriceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int salePriceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int supIdValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warrentValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brandValue {
            get {
                return this.brandValueField;
            }
            set {
                if ((object.ReferenceEquals(this.brandValueField, value) != true)) {
                    this.brandValueField = value;
                    this.RaisePropertyChanged("brandValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryValue {
            get {
                return this.countryValueField;
            }
            set {
                if ((object.ReferenceEquals(this.countryValueField, value) != true)) {
                    this.countryValueField = value;
                    this.RaisePropertyChanged("countryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameValue {
            get {
                return this.nameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.nameValueField, value) != true)) {
                    this.nameValueField = value;
                    this.RaisePropertyChanged("nameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodIdValue {
            get {
                return this.prodIdValueField;
            }
            set {
                if ((this.prodIdValueField.Equals(value) != true)) {
                    this.prodIdValueField = value;
                    this.RaisePropertyChanged("prodIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int purchPriceValue {
            get {
                return this.purchPriceValueField;
            }
            set {
                if ((this.purchPriceValueField.Equals(value) != true)) {
                    this.purchPriceValueField = value;
                    this.RaisePropertyChanged("purchPriceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int salePriceValue {
            get {
                return this.salePriceValueField;
            }
            set {
                if ((this.salePriceValueField.Equals(value) != true)) {
                    this.salePriceValueField = value;
                    this.RaisePropertyChanged("salePriceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int supIdValue {
            get {
                return this.supIdValueField;
            }
            set {
                if ((this.supIdValueField.Equals(value) != true)) {
                    this.supIdValueField = value;
                    this.RaisePropertyChanged("supIdValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warrentValue {
            get {
                return this.warrentValueField;
            }
            set {
                if ((object.ReferenceEquals(this.warrentValueField, value) != true)) {
                    this.warrentValueField = value;
                    this.RaisePropertyChanged("warrentValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refNameValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int supIdValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string add {
            get {
                return this.addField;
            }
            set {
                if ((object.ReferenceEquals(this.addField, value) != true)) {
                    this.addField = value;
                    this.RaisePropertyChanged("add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyNameValue {
            get {
                return this.companyNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameValueField, value) != true)) {
                    this.companyNameValueField = value;
                    this.RaisePropertyChanged("companyNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contactValue {
            get {
                return this.contactValueField;
            }
            set {
                if ((object.ReferenceEquals(this.contactValueField, value) != true)) {
                    this.contactValueField = value;
                    this.RaisePropertyChanged("contactValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryValue {
            get {
                return this.countryValueField;
            }
            set {
                if ((object.ReferenceEquals(this.countryValueField, value) != true)) {
                    this.countryValueField = value;
                    this.RaisePropertyChanged("countryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailValue {
            get {
                return this.emailValueField;
            }
            set {
                if ((object.ReferenceEquals(this.emailValueField, value) != true)) {
                    this.emailValueField = value;
                    this.RaisePropertyChanged("emailValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refNameValue {
            get {
                return this.refNameValueField;
            }
            set {
                if ((object.ReferenceEquals(this.refNameValueField, value) != true)) {
                    this.refNameValueField = value;
                    this.RaisePropertyChanged("refNameValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int supIdValue {
            get {
                return this.supIdValueField;
            }
            set {
                if ((this.supIdValueField.Equals(value) != true)) {
                    this.supIdValueField = value;
                    this.RaisePropertyChanged("supIdValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvotimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int employeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int invoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invotime {
            get {
                return this.InvotimeField;
            }
            set {
                if ((object.ReferenceEquals(this.InvotimeField, value) != true)) {
                    this.InvotimeField = value;
                    this.RaisePropertyChanged("Invotime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customer {
            get {
                return this.customerField;
            }
            set {
                if ((this.customerField.Equals(value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                if ((this.employeeIdField.Equals(value) != true)) {
                    this.employeeIdField = value;
                    this.RaisePropertyChanged("employeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int invoice {
            get {
                return this.invoiceField;
            }
            set {
                if ((this.invoiceField.Equals(value) != true)) {
                    this.invoiceField = value;
                    this.RaisePropertyChanged("invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product {
            get {
                return this.productField;
            }
            set {
                if ((this.productField.Equals(value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quan {
            get {
                return this.quanField;
            }
            set {
                if ((this.quanField.Equals(value) != true)) {
                    this.quanField = value;
                    this.RaisePropertyChanged("quan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tot {
            get {
                return this.totField;
            }
            set {
                if ((this.totField.Equals(value) != true)) {
                    this.totField = value;
                    this.RaisePropertyChanged("tot");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expectDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ordDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ordPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int suplierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expectDate {
            get {
                return this.expectDateField;
            }
            set {
                if ((this.expectDateField.Equals(value) != true)) {
                    this.expectDateField = value;
                    this.RaisePropertyChanged("expectDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ordDate {
            get {
                return this.ordDateField;
            }
            set {
                if ((this.ordDateField.Equals(value) != true)) {
                    this.ordDateField = value;
                    this.RaisePropertyChanged("ordDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ordId {
            get {
                return this.ordIdField;
            }
            set {
                if ((this.ordIdField.Equals(value) != true)) {
                    this.ordIdField = value;
                    this.RaisePropertyChanged("ordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ordPaid {
            get {
                return this.ordPaidField;
            }
            set {
                if ((this.ordPaidField.Equals(value) != true)) {
                    this.ordPaidField = value;
                    this.RaisePropertyChanged("ordPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product {
            get {
                return this.productField;
            }
            set {
                if ((this.productField.Equals(value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int suplier {
            get {
                return this.suplierField;
            }
            set {
                if ((this.suplierField.Equals(value) != true)) {
                    this.suplierField = value;
                    this.RaisePropertyChanged("suplier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSettings", Namespace="http://schemas.datacontract.org/2004/07/MetrixDistributedNew")]
    [System.SerializableAttribute()]
    public partial class UserSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.ICustomerServices")]
    public interface ICustomerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerSave", ReplyAction="http://tempuri.org/ICustomerServices/CustomerSaveResponse")]
        int CustomerSave(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerSave", ReplyAction="http://tempuri.org/ICustomerServices/CustomerSaveResponse")]
        System.Threading.Tasks.Task<int> CustomerSaveAsync(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerUpdate", ReplyAction="http://tempuri.org/ICustomerServices/CustomerUpdateResponse")]
        int CustomerUpdate(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerUpdate", ReplyAction="http://tempuri.org/ICustomerServices/CustomerUpdateResponse")]
        System.Threading.Tasks.Task<int> CustomerUpdateAsync(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerDelete", ReplyAction="http://tempuri.org/ICustomerServices/CustomerDeleteResponse")]
        int CustomerDelete(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerDelete", ReplyAction="http://tempuri.org/ICustomerServices/CustomerDeleteResponse")]
        System.Threading.Tasks.Task<int> CustomerDeleteAsync(Metrix.MetrixDistributedService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerSearch", ReplyAction="http://tempuri.org/ICustomerServices/CustomerSearchResponse")]
        Metrix.MetrixDistributedService.Customer CustomerSearch(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/CustomerSearch", ReplyAction="http://tempuri.org/ICustomerServices/CustomerSearchResponse")]
        System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Customer> CustomerSearchAsync(int customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServicesChannel : Metrix.MetrixDistributedService.ICustomerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.ICustomerServices>, Metrix.MetrixDistributedService.ICustomerServices {
        
        public CustomerServicesClient() {
        }
        
        public CustomerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CustomerSave(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerSave(customer);
        }
        
        public System.Threading.Tasks.Task<int> CustomerSaveAsync(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerSaveAsync(customer);
        }
        
        public int CustomerUpdate(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerUpdate(customer);
        }
        
        public System.Threading.Tasks.Task<int> CustomerUpdateAsync(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerUpdateAsync(customer);
        }
        
        public int CustomerDelete(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerDelete(customer);
        }
        
        public System.Threading.Tasks.Task<int> CustomerDeleteAsync(Metrix.MetrixDistributedService.Customer customer) {
            return base.Channel.CustomerDeleteAsync(customer);
        }
        
        public Metrix.MetrixDistributedService.Customer CustomerSearch(int customerId) {
            return base.Channel.CustomerSearch(customerId);
        }
        
        public System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Customer> CustomerSearchAsync(int customerId) {
            return base.Channel.CustomerSearchAsync(customerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.IEmployeeServices")]
    public interface IEmployeeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeSave", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeSaveResponse")]
        int EmployeeSave(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeSave", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeSaveResponse")]
        System.Threading.Tasks.Task<int> EmployeeSaveAsync(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeUpdate", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeUpdateResponse")]
        int EmployeeUpdate(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeUpdate", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeUpdateResponse")]
        System.Threading.Tasks.Task<int> EmployeeUpdateAsync(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeDelete", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeDeleteResponse")]
        int EmployeeDelete(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeDelete", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeDeleteResponse")]
        System.Threading.Tasks.Task<int> EmployeeDeleteAsync(Metrix.MetrixDistributedService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeSearch", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeSearchResponse")]
        Metrix.MetrixDistributedService.Employee EmployeeSearch(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/EmployeeSearch", ReplyAction="http://tempuri.org/IEmployeeServices/EmployeeSearchResponse")]
        System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Employee> EmployeeSearchAsync(int employeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServicesChannel : Metrix.MetrixDistributedService.IEmployeeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.IEmployeeServices>, Metrix.MetrixDistributedService.IEmployeeServices {
        
        public EmployeeServicesClient() {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EmployeeSave(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeSave(employee);
        }
        
        public System.Threading.Tasks.Task<int> EmployeeSaveAsync(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeSaveAsync(employee);
        }
        
        public int EmployeeUpdate(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeUpdate(employee);
        }
        
        public System.Threading.Tasks.Task<int> EmployeeUpdateAsync(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeUpdateAsync(employee);
        }
        
        public int EmployeeDelete(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeDelete(employee);
        }
        
        public System.Threading.Tasks.Task<int> EmployeeDeleteAsync(Metrix.MetrixDistributedService.Employee employee) {
            return base.Channel.EmployeeDeleteAsync(employee);
        }
        
        public Metrix.MetrixDistributedService.Employee EmployeeSearch(int employeeId) {
            return base.Channel.EmployeeSearch(employeeId);
        }
        
        public System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Employee> EmployeeSearchAsync(int employeeId) {
            return base.Channel.EmployeeSearchAsync(employeeId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.IProductServices")]
    public interface IProductServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductSave", ReplyAction="http://tempuri.org/IProductServices/ProductSaveResponse")]
        int ProductSave(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductSave", ReplyAction="http://tempuri.org/IProductServices/ProductSaveResponse")]
        System.Threading.Tasks.Task<int> ProductSaveAsync(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductUpdate", ReplyAction="http://tempuri.org/IProductServices/ProductUpdateResponse")]
        int ProductUpdate(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductUpdate", ReplyAction="http://tempuri.org/IProductServices/ProductUpdateResponse")]
        System.Threading.Tasks.Task<int> ProductUpdateAsync(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductDelete", ReplyAction="http://tempuri.org/IProductServices/ProductDeleteResponse")]
        int ProductDelete(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductDelete", ReplyAction="http://tempuri.org/IProductServices/ProductDeleteResponse")]
        System.Threading.Tasks.Task<int> ProductDeleteAsync(Metrix.MetrixDistributedService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductSearch", ReplyAction="http://tempuri.org/IProductServices/ProductSearchResponse")]
        Metrix.MetrixDistributedService.Product ProductSearch(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductServices/ProductSearch", ReplyAction="http://tempuri.org/IProductServices/ProductSearchResponse")]
        System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Product> ProductSearchAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServicesChannel : Metrix.MetrixDistributedService.IProductServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.IProductServices>, Metrix.MetrixDistributedService.IProductServices {
        
        public ProductServicesClient() {
        }
        
        public ProductServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ProductSave(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductSave(product);
        }
        
        public System.Threading.Tasks.Task<int> ProductSaveAsync(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductSaveAsync(product);
        }
        
        public int ProductUpdate(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductUpdate(product);
        }
        
        public System.Threading.Tasks.Task<int> ProductUpdateAsync(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductUpdateAsync(product);
        }
        
        public int ProductDelete(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductDelete(product);
        }
        
        public System.Threading.Tasks.Task<int> ProductDeleteAsync(Metrix.MetrixDistributedService.Product product) {
            return base.Channel.ProductDeleteAsync(product);
        }
        
        public Metrix.MetrixDistributedService.Product ProductSearch(int productId) {
            return base.Channel.ProductSearch(productId);
        }
        
        public System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Product> ProductSearchAsync(int productId) {
            return base.Channel.ProductSearchAsync(productId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.ISupplierServices")]
    public interface ISupplierServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierSave", ReplyAction="http://tempuri.org/ISupplierServices/SupplierSaveResponse")]
        int SupplierSave(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierSave", ReplyAction="http://tempuri.org/ISupplierServices/SupplierSaveResponse")]
        System.Threading.Tasks.Task<int> SupplierSaveAsync(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierUpdate", ReplyAction="http://tempuri.org/ISupplierServices/SupplierUpdateResponse")]
        int SupplierUpdate(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierUpdate", ReplyAction="http://tempuri.org/ISupplierServices/SupplierUpdateResponse")]
        System.Threading.Tasks.Task<int> SupplierUpdateAsync(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierDelete", ReplyAction="http://tempuri.org/ISupplierServices/SupplierDeleteResponse")]
        int SupplierDelete(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierDelete", ReplyAction="http://tempuri.org/ISupplierServices/SupplierDeleteResponse")]
        System.Threading.Tasks.Task<int> SupplierDeleteAsync(Metrix.MetrixDistributedService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierSearch", ReplyAction="http://tempuri.org/ISupplierServices/SupplierSearchResponse")]
        Metrix.MetrixDistributedService.Supplier SupplierSearch(int supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplierServices/SupplierSearch", ReplyAction="http://tempuri.org/ISupplierServices/SupplierSearchResponse")]
        System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Supplier> SupplierSearchAsync(int supplierId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupplierServicesChannel : Metrix.MetrixDistributedService.ISupplierServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.ISupplierServices>, Metrix.MetrixDistributedService.ISupplierServices {
        
        public SupplierServicesClient() {
        }
        
        public SupplierServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SupplierSave(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierSave(supplier);
        }
        
        public System.Threading.Tasks.Task<int> SupplierSaveAsync(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierSaveAsync(supplier);
        }
        
        public int SupplierUpdate(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierUpdate(supplier);
        }
        
        public System.Threading.Tasks.Task<int> SupplierUpdateAsync(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierUpdateAsync(supplier);
        }
        
        public int SupplierDelete(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierDelete(supplier);
        }
        
        public System.Threading.Tasks.Task<int> SupplierDeleteAsync(Metrix.MetrixDistributedService.Supplier supplier) {
            return base.Channel.SupplierDeleteAsync(supplier);
        }
        
        public Metrix.MetrixDistributedService.Supplier SupplierSearch(int supplierId) {
            return base.Channel.SupplierSearch(supplierId);
        }
        
        public System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Supplier> SupplierSearchAsync(int supplierId) {
            return base.Channel.SupplierSearchAsync(supplierId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.IInvoiceServices")]
    public interface IInvoiceServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/InvoiceSave", ReplyAction="http://tempuri.org/IInvoiceServices/InvoiceSaveResponse")]
        int InvoiceSave(Metrix.MetrixDistributedService.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/InvoiceSave", ReplyAction="http://tempuri.org/IInvoiceServices/InvoiceSaveResponse")]
        System.Threading.Tasks.Task<int> InvoiceSaveAsync(Metrix.MetrixDistributedService.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/SaveInvoiceList", ReplyAction="http://tempuri.org/IInvoiceServices/SaveInvoiceListResponse")]
        int SaveInvoiceList(Metrix.MetrixDistributedService.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/SaveInvoiceList", ReplyAction="http://tempuri.org/IInvoiceServices/SaveInvoiceListResponse")]
        System.Threading.Tasks.Task<int> SaveInvoiceListAsync(Metrix.MetrixDistributedService.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/InvoiceProductSearch", ReplyAction="http://tempuri.org/IInvoiceServices/InvoiceProductSearchResponse")]
        Metrix.MetrixDistributedService.Invoice InvoiceProductSearch(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceServices/InvoiceProductSearch", ReplyAction="http://tempuri.org/IInvoiceServices/InvoiceProductSearchResponse")]
        System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Invoice> InvoiceProductSearchAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvoiceServicesChannel : Metrix.MetrixDistributedService.IInvoiceServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.IInvoiceServices>, Metrix.MetrixDistributedService.IInvoiceServices {
        
        public InvoiceServicesClient() {
        }
        
        public InvoiceServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InvoiceSave(Metrix.MetrixDistributedService.Invoice invoice) {
            return base.Channel.InvoiceSave(invoice);
        }
        
        public System.Threading.Tasks.Task<int> InvoiceSaveAsync(Metrix.MetrixDistributedService.Invoice invoice) {
            return base.Channel.InvoiceSaveAsync(invoice);
        }
        
        public int SaveInvoiceList(Metrix.MetrixDistributedService.Invoice invoice) {
            return base.Channel.SaveInvoiceList(invoice);
        }
        
        public System.Threading.Tasks.Task<int> SaveInvoiceListAsync(Metrix.MetrixDistributedService.Invoice invoice) {
            return base.Channel.SaveInvoiceListAsync(invoice);
        }
        
        public Metrix.MetrixDistributedService.Invoice InvoiceProductSearch(int productId) {
            return base.Channel.InvoiceProductSearch(productId);
        }
        
        public System.Threading.Tasks.Task<Metrix.MetrixDistributedService.Invoice> InvoiceProductSearchAsync(int productId) {
            return base.Channel.InvoiceProductSearchAsync(productId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.IOrderServices")]
    public interface IOrderServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderSave", ReplyAction="http://tempuri.org/IOrderServices/OrderSaveResponse")]
        int OrderSave(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderSave", ReplyAction="http://tempuri.org/IOrderServices/OrderSaveResponse")]
        System.Threading.Tasks.Task<int> OrderSaveAsync(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderUpdate", ReplyAction="http://tempuri.org/IOrderServices/OrderUpdateResponse")]
        int OrderUpdate(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderUpdate", ReplyAction="http://tempuri.org/IOrderServices/OrderUpdateResponse")]
        System.Threading.Tasks.Task<int> OrderUpdateAsync(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderDelete", ReplyAction="http://tempuri.org/IOrderServices/OrderDeleteResponse")]
        int OrderDelete(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/OrderDelete", ReplyAction="http://tempuri.org/IOrderServices/OrderDeleteResponse")]
        System.Threading.Tasks.Task<int> OrderDeleteAsync(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/SaveOrderList", ReplyAction="http://tempuri.org/IOrderServices/SaveOrderListResponse")]
        int SaveOrderList(Metrix.MetrixDistributedService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderServices/SaveOrderList", ReplyAction="http://tempuri.org/IOrderServices/SaveOrderListResponse")]
        System.Threading.Tasks.Task<int> SaveOrderListAsync(Metrix.MetrixDistributedService.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServicesChannel : Metrix.MetrixDistributedService.IOrderServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.IOrderServices>, Metrix.MetrixDistributedService.IOrderServices {
        
        public OrderServicesClient() {
        }
        
        public OrderServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int OrderSave(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderSave(order);
        }
        
        public System.Threading.Tasks.Task<int> OrderSaveAsync(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderSaveAsync(order);
        }
        
        public int OrderUpdate(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderUpdate(order);
        }
        
        public System.Threading.Tasks.Task<int> OrderUpdateAsync(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderUpdateAsync(order);
        }
        
        public int OrderDelete(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderDelete(order);
        }
        
        public System.Threading.Tasks.Task<int> OrderDeleteAsync(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.OrderDeleteAsync(order);
        }
        
        public int SaveOrderList(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.SaveOrderList(order);
        }
        
        public System.Threading.Tasks.Task<int> SaveOrderListAsync(Metrix.MetrixDistributedService.Order order) {
            return base.Channel.SaveOrderListAsync(order);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SignIn", ReplyAction="http://tempuri.org/ILoginService/SignInResponse")]
        int SignIn(Metrix.MetrixDistributedService.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SignIn", ReplyAction="http://tempuri.org/ILoginService/SignInResponse")]
        System.Threading.Tasks.Task<int> SignInAsync(Metrix.MetrixDistributedService.user user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : Metrix.MetrixDistributedService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.ILoginService>, Metrix.MetrixDistributedService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SignIn(Metrix.MetrixDistributedService.user user) {
            return base.Channel.SignIn(user);
        }
        
        public System.Threading.Tasks.Task<int> SignInAsync(Metrix.MetrixDistributedService.user user) {
            return base.Channel.SignInAsync(user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetrixDistributedService.IUserSettingsServices")]
    public interface IUserSettingsServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSettingsServices/SignUp", ReplyAction="http://tempuri.org/IUserSettingsServices/SignUpResponse")]
        int SignUp(Metrix.MetrixDistributedService.UserSettings usersett);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSettingsServices/SignUp", ReplyAction="http://tempuri.org/IUserSettingsServices/SignUpResponse")]
        System.Threading.Tasks.Task<int> SignUpAsync(Metrix.MetrixDistributedService.UserSettings usersett);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSettingsServices/ChangeUser", ReplyAction="http://tempuri.org/IUserSettingsServices/ChangeUserResponse")]
        int ChangeUser(Metrix.MetrixDistributedService.UserSettings usersett);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSettingsServices/ChangeUser", ReplyAction="http://tempuri.org/IUserSettingsServices/ChangeUserResponse")]
        System.Threading.Tasks.Task<int> ChangeUserAsync(Metrix.MetrixDistributedService.UserSettings usersett);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserSettingsServicesChannel : Metrix.MetrixDistributedService.IUserSettingsServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSettingsServicesClient : System.ServiceModel.ClientBase<Metrix.MetrixDistributedService.IUserSettingsServices>, Metrix.MetrixDistributedService.IUserSettingsServices {
        
        public UserSettingsServicesClient() {
        }
        
        public UserSettingsServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSettingsServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSettingsServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSettingsServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SignUp(Metrix.MetrixDistributedService.UserSettings usersett) {
            return base.Channel.SignUp(usersett);
        }
        
        public System.Threading.Tasks.Task<int> SignUpAsync(Metrix.MetrixDistributedService.UserSettings usersett) {
            return base.Channel.SignUpAsync(usersett);
        }
        
        public int ChangeUser(Metrix.MetrixDistributedService.UserSettings usersett) {
            return base.Channel.ChangeUser(usersett);
        }
        
        public System.Threading.Tasks.Task<int> ChangeUserAsync(Metrix.MetrixDistributedService.UserSettings usersett) {
            return base.Channel.ChangeUserAsync(usersett);
        }
    }
}
